chore: update Conventional Commits check msg

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,5 +1,6 @@
+#!/bin/sh
 if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
-    echo -e "Aborting commit. Your commit message is invalid. \n More about Conventional Commits:https://www.conventionalcommits.org/en/v1.0.0/" >&2
+    echo -e "Aborting commit. Your commit message is invalid you need to follow the Conventional Commits standard. \n More about Conventional Commits: https://www.conventionalcommits.org/en/v1.0.0/" >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
